### ISSUE TITLE
Feature Request: Schematics via //pos

### ISSUE THREAD

**Issue by PocketMiner92** [CzechPMDevs/BuilderTools#189] opened 2021-12-20 13:12 UTC
**Is your feature request related to a problem? Please describe.** Schematic Import with Position Selector. For Example a Plot Schematic.
Its a blame to add a Plot Schematic because its pasted randomly in a World.
Its easier to do this with //pos 1 //pos 2 //setschem.
You can place Schematics with this Option easiely and perfect.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VixikHD** [comment] 2021-12-24 15:03
Paste position is relative to player's position. Also using //pos1 and //pos2 to paste schematics inside does not really makes sense for me in terms of selection size. For example, when schematics dimensions are 1512x124x1245 and the selection dimensions are 1504x123x1243, how shall the plugin work in this situation? The problem is it's hard to make selection of exact size as schematics. Due to this problem and invalid usage of the issue template, I am closing this for now. If you want me to work on it, please specify how should plugin work in this situation, and format the issue content regarding to template.

**Closed by VixikHD** 2021-12-24 15:03 UTC
Labels: Feature request
