### ISSUE TITLE
ItemCase isn't compatible with BuilderTools

### ISSUE THREAD

**Issue by Svetrik** [CzechPMDevs/BuilderTools#69] opened 2019-08-06 08:07 UTC
Everytime when I type for example //set it kicks me out with reason: Internal server error. It is giving me the error with every command.

**Comment by piyushbest** [comment] 2019-08-06 08:14
Give crash, what plugin version u use so we can fix i thinkbu not use last version

**Comment by piyushbest** [comment] 2019-08-06 08:16
https://poggit.pmmp.io/r/62327/BuilderTools_dev-66.phar

**Comment by piyushbest** [comment] 2019-08-06 08:16
Use this then try

**Comment by Melon-Dude** [comment] 2019-08-08 20:36
I had this problem myself, but looking into the crash data, I found that the plugin "ItemCase" was interfering with this command in someway.

**Comment by GamakCZ** [comment] 2019-08-10 17:41
Can you send me the crash? I would make the plugin compatible with ItemCase.

**Comment by aref0448** [comment] 2021-04-24 19:45
The Builder Tools plugin interferes with the person item and itemcase the plugin to crash and not work.

**Comment by UnEnanoMas** [comment] 2021-04-24 20:09
ItemCase has not been updated for 2 years, the error has already been reported to its corresponding plugin, the problem is generated by itemcase, not buildertools (I say this because it has happened to me with other plugins that have interfered with itemcase)

@aref0448

**Comment by aref0448** [comment] 2021-04-25 16:51
Is there a way to fix the bug?
@UnEnanoMas

**Comment by UnEnanoMas** [comment] 2021-04-25 17:33
As far as I know no, it happened to me with another plugin and I create a dependency, if I deleted itemcase the server would not work, it was very rare.

I had to remove many plugins to correct my error, but I never get an error with buildertools, still don't use it, itemcase is outdated, put the objects in the frames, it's still the same

**Comment by VixikHD** [comment] 2021-04-25 18:02
I could not reproduce any crashes with this build https://github.com/poggit-orphanage/ItemCase/pull/8

**Comment by UnEnanoMas** [comment] 2021-04-25 18:03
I think it is better to close the issue, it has been a long time

**Comment by aref0448** [comment] 2021-04-25 21:01
The problem is that the items inside the frame are dropped by the players and I have not yet found a plugin to fix this problem.
@UnEnanoMas

**Comment by VixikHD** [comment] 2021-04-25 21:03
> The problem is that the items inside the frame are dropped by the players and I have not yet found a plugin to fix this problem.
> @UnEnanoMas

Try reproducing the issue with [this](https://github.com/poggit-orphanage/ItemCase/pull/8) version. If you reproduce the bug, please send me video with it.

**Comment by aref0448** [comment] 2021-04-25 21:06
Thank you, I will try tomorrow and if there is a problem, we will let you know, and if the problem is solved, I will let you know♡

@VixikHD

**Comment by aref0448** [comment] 2021-05-05 16:43
Not work

**Comment by VixikHD** [comment] 2021-05-05 17:56
Then send me error from the console you are getting.

**Comment by aref0448** [comment] 2021-05-07 01:18
The plug is not run that wants to give an error

**Comment by VixikHD** [comment] 2021-05-07 06:03
You have to use [latest version](https://poggit.pmmp.io/r/124329/ItemCase_dev-20.phar) of ItemCase plugin

**Comment by aref0448** [comment] 2021-05-07 12:58
Even for the Minecraft version 1.16.20?

**Closed** 2021-11-12 22:55 UTC
Labels: Bug: Plugin side, Todo
